version: '3.1'

services:
  todo_next_postgresql:
    image: postgres:13.9
    restart: always
    ports: 
      - 5432:5432
    volumes: 
      - "/db:/data"
    environment:
      - POSTGRES_PASSWORD=localdevpass
